<a href="https://colab.research.google.com/github/Nazif-25/Python_Basics/blob/main/A8_Sec19_23301482_MOHAMMAD_NAZIF_RAHMAN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [10]:
heap = np.array([0]*10)
print(heap)

[0 0 0 0 0 0 0 0 0 0]


#Task 1

In [8]:
class MinHeap:
    def __init__(self, heap_length=10):
        self.heap = np.array([0]*(heap_length+1))
        self.last_index = 1

    def insert(self, value):
        if self.last_index >= len(self.heap):
            print("heap is full!")
            return
        self.heap[self.last_index] = value
        self.swim(self.last_index)
        self.last_index += 1

    def swim(self, child_index):
        if child_index == 1:
            return
        parent_index = child_index//2
        if self.heap[parent_index] > self.heap[child_index]:
            temp = self.heap[parent_index]
            self.heap[parent_index] = self.heap[child_index]
            self.heap[child_index] = temp
            self.swim(parent_index)
        return

    def extractMin(self):
        if self.last_index == 1:
            print("heap is empty")
            return
        temp = self.heap[1]
        self.heap[1] = self.heap[self.last_index-1]
        self.heap[self.last_index-1] = temp
        self.last_index -= 1
        self.sink(1)
        print(f"{temp} is removed")
        return temp

    def sink(self, parent_index):
        left_index = 2*parent_index
        right_index = 2*parent_index+1

        if left_index >= self.last_index and right_index >= self.last_index:
            return
        if left_index < self.last_index and right_index < self.last_index:
            if self.heap[left_index] < self.heap[right_index]:
                temp = self.heap[left_index]
                self.heap[left_index] = self.heap[parent_index]
                self.heap[parent_index] = temp
                self.sink(left_index)

            else:
                temp = self.heap[right_index]
                self.heap[right_index] = self.heap[parent_index]
                self.heap[parent_index] = temp
                self.sink(right_index)


        elif left_index < self.last_index:
            temp = self.heap[left_index]
            self.heap[left_index] = self.heap[parent_index]
            self.heap[parent_index] = temp
            self.sink(left_index)

        return

    def print_heap(self):
        print(self.heap[:self.last_index])

    def sort(self):
        original_size = self.last_index
        for i in range(self.last_index-1, 0, -1):
            temp = self.heap[1]
            self.heap[1] = self.heap[i]
            self.heap[i] = temp
            self.last_index -= 1
            self.sink(1)
        self.last_index = original_size

    def print_sorted(self):
        self.sort()
        print(self.heap[:self.last_index])

heap = MinHeap(5)

heap.insert(15)
heap.insert(5)
heap.insert(20)
heap.insert(10)

heap.print_heap()

heap.extractMin()

heap.print_heap()

heap.print_sorted()

[ 0  5 10 20 15]
5 is removed
[ 0 10 15 20]
[ 0 20 15 10]


#Task 2

In [17]:
class MaxHeap:
    def __init__(self, heap_length=10):
        self.heap = np.array([0]*(heap_length+1))
        self.last_index = 1

    def insert(self, value):
        if self.last_index >= len(self.heap):
            print("heap is full!")
            return
        self.heap[self.last_index] = value
        self.swim(self.last_index)
        self.last_index += 1

    def swim(self, child_index):
        if child_index == 1:
            return
        parent_index = child_index//2
        if self.heap[parent_index]<self.heap[child_index]:
            temp = self.heap[parent_index]
            self.heap[parent_index] = self.heap[child_index]
            self.heap[child_index] = temp
            self.swim(parent_index)
        return

    def extractMax(self):
        if self.last_index == 1:
            print("heap is empty")
            return
        temp = self.heap[1]
        self.heap[1] = self.heap[self.last_index-1]
        self.heap[self.last_index-1] = temp
        self.last_index -= 1
        self.sink(1)
        return temp

    def sink(self, parent_index):
        left_index = 2*parent_index
        right_index = 2*parent_index+1
        largest = parent_index

        if left_index < self.last_index and self.heap[left_index] > self.heap[largest]:
            largest = left_index
        if right_index < self.last_index and self.heap[right_index] > self.heap[largest]:
            largest = right_index

        if largest != parent_index:
            temp = self.heap[parent_index]
            self.heap[parent_index] = self.heap[largest]
            self.heap[largest] = temp
            self.sink(largest)

    def print_heap(self):
        print(self.heap[:self.last_index])

    def sort(self):
        original_size = self.last_index
        for i in range(self.last_index-1, 0, -1):
            temp = self.heap[i]
            self.heap[i] = self.heap[1]
            self.heap[1] = temp
            self.last_index -= 1
            self.sink(1)
        self.last_index = original_size

    def print_sorted(self):
        self.sort()
        print(self.heap[:self.last_index])

heap = MaxHeap(5)
heap.insert(15)
heap.insert(5)
heap.insert(20)
heap.insert(15)
heap.insert(10)
heap.print_heap()
print(heap.extractMax())
heap.print_heap()
heap.print_sorted()

[ 0 20 15 15  5 10]
20
[ 0 15 10 15  5]
[ 0  5 10 15 15]


#Task 4


In [15]:
class MaxHeap:
    def __init__(self, heap_length=10):
        self.heap = np.array([0]*(heap_length+1))
        self.last_index = 1

    def insert(self, value):
        if self.last_index >= len(self.heap):
            print("heap is full!")
            return
        self.heap[self.last_index] = value
        self.swim(self.last_index)
        self.last_index += 1

    def swim(self, child_index):
        if child_index == 1:
            return
        parent_index = child_index//2
        if self.heap[parent_index]<self.heap[child_index]:
            temp = self.heap[parent_index]
            self.heap[parent_index] = self.heap[child_index]
            self.heap[child_index] = temp
            self.swim(parent_index)
        return

    def extractMax(self):
        if self.last_index == 1:
            print("heap is empty")
            return
        temp = self.heap[1]
        self.heap[1] = self.heap[self.last_index-1]
        self.heap[self.last_index-1] = temp
        self.last_index -= 1
        self.sink(1)
        # print(f"{temp} is removed")
        return temp

    def sink(self, parent_index):
        left_index = 2*parent_index
        right_index = 2*parent_index+1
        largest = parent_index

        if left_index < self.last_index and self.heap[left_index] > self.heap[largest]:
            largest = left_index
        if right_index < self.last_index and self.heap[right_index] > self.heap[largest]:
            largest = right_index

        if largest != parent_index:
            temp = self.heap[parent_index]
            self.heap[parent_index] = self.heap[largest]
            self.heap[largest] = temp
            self.sink(largest)

    def print_heap(self):
        print(self.heap[:self.last_index])

    def sort(self):
        original_size = self.last_index
        for i in range(self.last_index-1, 0, -1):
            temp = self.heap[i]
            self.heap[i] = self.heap[1]
            self.heap[1] = temp
            self.last_index -= 1
            self.sink(1)
        self.last_index = original_size

    def print_sorted(self):
        self.sort()
        print(self.heap[:self.last_index])

    def extract(self, k, arr, i=0):
        if k == 0:
            print(arr)
            return
        arr[i] = self.extractMax()
        self.extract(k-1, arr, i+1)

nums = [4, 10, 2, 8, 6, 7]
heap = MaxHeap(len(nums))
for i in nums:
    heap.insert(i)
heap.print_heap()
heap.extract(3, np.array([0]*3))

[ 0 10  8  7  4  6  2]
[10  8  7]


#Practice

In [11]:
class MaxHeap:
    def __init__(self, capacity):
        self.capacity = capacity
        self.heap = [0] * capacity
        self.size = 0

    def insert(self, value):
        if self.size == self.capacity:
            print("Heap is full")
            return
        self.heap[self.size] = value
        self._swim(self.size)
        self.size += 1

    def _swim(self, child_index):
        if child_index == 0:
            return
        parent_index = child_index//2
        if self.heap[parent_index]<self.heap[child_index]:
            temp = self.heap[parent_index]
            self.heap[parent_index] = self.heap[child_index]
            self.heap[child_index] = temp
            self._swim(parent_index)
        return

    def _parent(self, index):
        return (index - 1) // 2

    def extractMax(self):
        if self.size == 0:
            print("Heap is empty")
            return
        max_val = self.heap[0]
        self._swap(0, self.size - 1)
        self.size -= 1
        self.sink(0)
        return max_val

    def sink(self, index):
        largest = index
        left = 2 * index + 1
        right = 2 * index + 2

        if left < self.size and self.heap[left] > self.heap[largest]:
            largest = left
        if right < self.size and self.heap[right] > self.heap[largest]:
            largest = right

        if largest != index:
            self._swap(index, largest)
            self.sink(largest)

    def _swap(self, i, j):
        self.heap[i], self.heap[j] = self.heap[j], self.heap[i]

    def heap_sort(self):
        original_size = self.size
        for i in range(self.size - 1, 0, -1):
            self._swap(0, i)
            self.size -= 1
            self._heapify(0)
        self.size = original_size

    def print_heap(self):
        print(self.heap[:self.size])

    def print_sorted(self):
        self.heap_sort()
        print(self.heap[:self.size])

    def extract(self, k, arr, i=0):
        if k == 0:
            print(arr)
            return
        arr[i] = self.extractMax()
        self.extract(k-1, arr, i+1)

nums = [4, 10, 2, 8, 6, 7]
heap = MaxHeap(len(nums))
for i in nums:
    heap.insert(i)
heap.print_heap()
heap.extract(3, np.array([0]*3))

[10, 8, 7, 4, 2, 6]
[10  8  7]


In [12]:
class MaxHeap:
    def __init__(self, capacity):
        self.capacity = capacity
        self.heap = [0] * capacity
        self.size = 0

    def insert(self, value):
        if self.size == self.capacity:
            print("Heap is full")
            return
        self.heap[self.size] = value
        self._swim(self.size)
        self.size += 1

    def _swim(self, child_index):
        if child_index == 0:
            return
        parent_index = child_index//2
        if self.heap[parent_index]<self.heap[child_index]:
            temp = self.heap[parent_index]
            self.heap[parent_index] = self.heap[child_index]
            self.heap[child_index] = temp
            self._swim(parent_index)
        return

    def _parent(self, index):
        return (index - 1) // 2

    def extractMax(self):
        if self.size == 0:
            print("Heap is empty")
            return
        max_val = self.heap[0]
        self._swap(0, self.size - 1)
        self.size -= 1
        self.sink(0)
        return max_val

    def sink(self, index):
        largest = index
        left = 2 * index + 1
        right = 2 * index + 2

        if left < self.size and self.heap[left] > self.heap[largest]:
            largest = left
        if right < self.size and self.heap[right] > self.heap[largest]:
            largest = right

        if largest != index:
            self._swap(index, largest)
            self.sink(largest)

    def _swap(self, i, j):
        self.heap[i], self.heap[j] = self.heap[j], self.heap[i]

    def heap_sort(self):
        original_size = self.size
        for i in range(self.size - 1, 0, -1):
            self._swap(0, i)
            self.size -= 1
            self._heapify(0)
        self.size = original_size

    def print_heap(self):
        print(self.heap[:self.size])

    def print_sorted(self):
        self.heap_sort()
        print(self.heap[:self.size])

    def extract(self, k, arr=[]):
        if k == 0:
            print(arr)
            return
        arr += [self.extractMax()]
        self.extract(k-1, arr)

    def extract(self, k, arr, i=0):
        if k == 0:
            print(arr)
            return
        arr[i] = self.extractMax()
        self.extract(k-1, arr, i+1)

nums = [4, 10, 2, 8, 6, 7]
heap = MaxHeap(len(nums))
for i in nums:
    heap.insert(i)
heap.print_heap()
heap.extract(3, np.array([0]*3))

[10, 8, 7, 4, 2, 6]
[10  8  7]
