<a href="https://colab.research.google.com/github/Nazif-25/Python_Basics/blob/main/Graphs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import numpy as np

#Queue

In [2]:
class Node:
    def __init__(self, elem):
        self.elem = elem
        self.next = None

class Queue:
    def __init__(self):
        self.front = self.rear = None

    def enqueue(self, elem):
        new_node = Node(elem)
        if self.rear is None:
            self.front = self.rear = new_node
            return
        self.rear.next = new_node
        self.rear = new_node

    def dequeue(self):
        if self.is_empty():
            raise IndexError("Queue is empty")
        removed_elem = self.front.elem
        self.front = self.front.next
        if self.front is None:
            self.rear = None
        return removed_elem

    def peek(self):
        if self.is_empty():
            raise IndexError("Queue is empty")
        return self.front.elem

    def is_empty(self):
        return self.front is None

#Stack

In [9]:
class Stack:
    def __init__(self):
        self.top = None

    def push(self, elem):
        new_node = Node(elem)
        new_node.next = self.top
        self.top = new_node

    def pop(self):
        if self.is_empty():
            raise IndexError("Stack is empty")
        popped_elem = self.top.elem
        self.top = self.top.next
        return popped_elem

    def peek(self):
        if self.is_empty():
            raise IndexError("Stack is empty")
        return self.top.elem

    def is_empty(self):
        return self.top is None

#Graphs

In [10]:
# adjacency matrix
import numpy as np
def create_matrix():
    # here graph is a matrix
    graph = np.zeros((5,5), dtype = int)
    # matrix[row][col] = edge_weight
    graph[0][2] = 15
    graph[0][4] = 7
    graph[1][2] = 10
    graph[1][3] = 19
    graph[1][4] = 12
    graph[2][0] = 15
    graph[2][1] = 10
    graph[2][3] = 20
    graph[3][1] = 19
    graph[3][2] = 20
    graph[3][4] = 8
    graph[4][0] = 7
    graph[4][1] = 12
    graph[4][3] = 8
    return graph

In [15]:
graph = create_matrix()
print(graph)

[[ 0  0 15  0  7]
 [ 0  0 10 19 12]
 [15 10  0 20  0]
 [ 0 19 20  0  8]
 [ 7 12  0  8  0]]


In [ ]:
#      0  1  2  3  4
# 0 [[ 0  0 15  0  7]
# 1  [ 0  0 10 19 12]
# 2  [15 10  0 20  0]
# 3  [ 0 19 20  0  8]
# 4  [ 7 12  0  8  0]]
# vertex 1 has no connections with 0 or itself
# vertex 1 has connections with 2 with weight 10

# the degree of a vertex is the number of edges connected to that vertex
# degree of 1 is 3
# if we iterate row 1 then we get degree of vertex 1

#DFS

In [18]:
def DFS(graph, start):
    total_vertex = len(graph)
    visited = np.array([False]*total_vertex)
    S = Stack()
    visited[start] = True
    S.push(start)
    while S.is_empty() == False:
        u = S.pop()
        print(u)
        for v in range(total_vertex):
            if graph[u][v] != 0 and visited[v] == False:
                visited[v] = True
                S.push(v)
DFS(graph, 2)


2
3
4
1
0


#BFS

In [19]:
def BFS(graph, start):
    total_vertex = len(graph)
    visited = np.array([False]*total_vertex)
    Q = Queue()
    visited[start] = True
    Q.enqueue(start)
    while Q.is_empty() == False:
        u = Q.dequeue()
        print(u)
        for v in range(total_vertex):
            if graph[u][v] != 0 and visited[v] == False:
                visited[v] = True
                Q.enqueue(v)
BFS(graph, 2)

2
0
1
3
4


#Degree

In [ ]:
def get_degree(matrix, v):
    rows = len(matrix)
    cols = len(matrix[0])
    count = 0
    for r in range(rows):
        if r == v:
            for c in range(cols):
                if matrix[r][c] != 0:
                    count+=1
                    print(matrix[r][c])
    return count

print(get_degree(graph, 1))

10
19
12
3


In [ ]:
# if the above was a directed graph we would have found the
# outdegree in the same manner, i.e. iterate the row

# to get in degree we just need to check column-wise

In [ ]:
class Node:
    def __init__(self, v, w):
        self.v = v

        # e_w = edge_weight
        self.e_w = w

        self.next = None

# u = into_vertex
# v = out_of_vertex
def add_edge(graph, u, v, weight):
    # new_node = v   is the source
    new_node = Node(v, weight)

    # new_node.next = u   is the destination
    new_node.next = graph[u]

    graph[u] = new_node
    return

#  v -> u


def create_adjacency_list():
    # this is how we create a fixed sized array : [None, None, None, None, None]
    graph = np.array([None]*5)
    add_edge(graph, 0, 2, 15)
    add_edge(graph, 0, 4, 7)
    add_edge(graph, 1, 2, 10)
    add_edge(graph, 1, 3, 19)
    add_edge(graph, 1, 4, 12)
    add_edge(graph, 2, 0, 15)
    add_edge(graph, 2, 1, 10)
    add_edge(graph, 2, 3, 20)
    add_edge(graph, 3, 1, 19)
    add_edge(graph, 3, 2, 20)
    add_edge(graph, 3, 4, 8)
    add_edge(graph, 4, 0, 7)
    add_edge(graph, 4, 1, 12)
    add_edge(graph, 4, 3, 8)
    return graph

In [ ]:
graph = create_adjacency_list()
def print_LL(head):
    temp = head
    while temp!= None:
        print(f" connected to {temp.v}, edge weight = {temp.e_w}")
        temp =temp.next
    return


# print_LL(graph[1])
print_LL(graph[2])


 connected to 3, edge weight = 20
 connected to 1, edge weight = 10
 connected to 0, edge weight = 15


#Adjacency Matrix

In [ ]:
class Node:
    def __init__(self, data):
        self.data = data


class Graph:
    def __init__(self, size):
        self.nodesList = []
        # self.matrix = [[0] * size for _ in range(size)]
        self.matrix = np.zeros((size, size), dtype=int)

    def add_node(self, node):
        # self.nodesList.append(node)
        self.nodesList += [node]

    def add_edge(self, src, dst):
        self.matrix[src][dst] = 1

    def check_edge(self, src, dst):
        if  self.matrix[src][dst] == 1:
            return True
        return False

    def print_graph(self):
        rows = len(self.matrix)
        cols = len(self.matrix[0])
        print("  ", end="")

        for node in self.nodesList:
            print(f"{node.data} ", end="")
        print()

        for r in range(rows):
            print(f"{self.nodesList[r].data} ", end="")
            for c in range(cols):
                print(f"{self.matrix[r][c]} ", end="")
            print()


if __name__ == "__main__":
    graph = Graph(5)

    graph.add_node(Node('A'))
    graph.add_node(Node('B'))
    graph.add_node(Node('C'))
    graph.add_node(Node('D'))
    graph.add_node(Node('E'))

    graph.add_edge(0, 1)
    graph.add_edge(1, 2)
    graph.add_edge(1, 4)
    graph.add_edge(2, 3)
    graph.add_edge(2, 4)
    graph.add_edge(4, 0)
    graph.add_edge(4, 2)

    graph.print_graph()
    print(graph.check_edge(0,1))


  A B C D E 
A 0 1 0 0 0 
B 0 0 1 0 1 
C 0 0 0 1 1 
D 0 0 0 0 0 
E 1 0 1 0 0 
True


In [ ]:
class Node:
    def __init__(self, data):
        self.data = data


class Graph:
    def __init__(self, size):
        self.nodesList = []
        # self.matrix = [[0] * size for _ in range(size)]
        self.matrix = np.zeros((size, size), dtype=int)

    def add_node(self, elem):
        node = Node(elem)
        self.nodesList += [node]

    def add_edge(self, src, dst):
        self.matrix[src][dst] = 1

    def check_edge(self, src, dst):
        if  self.matrix[src][dst] == 1:
            return True
        return False

    def print_graph(self):
        rows = len(self.matrix)
        cols = len(self.matrix[0])
        print("  ", end="")

        for node in self.nodesList:
            print(f"{node.data} ", end="")
        print()

        for r in range(rows):
            print(f"{self.nodesList[r].data} ", end="")
            for c in range(cols):
                print(f"{self.matrix[r][c]} ", end="")
            print()


if __name__ == "__main__":
    graph = Graph(5)

    graph.add_node('A')
    graph.add_node('B')
    graph.add_node('C')
    graph.add_node('D')
    graph.add_node('E')

    graph.add_edge(0, 1)
    graph.add_edge(1, 2)
    graph.add_edge(1, 4)
    graph.add_edge(2, 3)
    graph.add_edge(2, 4)
    graph.add_edge(4, 0)
    graph.add_edge(4, 2)

    graph.print_graph()
    print(graph.check_edge(0,1))


  A B C D E 
A 0 1 0 0 0 
B 0 0 1 0 1 
C 0 0 0 1 1 
D 0 0 0 0 0 
E 1 0 1 0 0 
True


#Adjacency List

In [ ]:
class Node:
    def __init__(self, data):
        self.data = data

class Graph:
    def __init__(self):
        self.alist = []

    def add_node(self, elem):
        node = Node(elem)
        self.alist.append([node])  # Each sublist starts with its head node

    def add_edge(self, src, dst):
        src_list = self.alist[src]
        dst_node = self.alist[dst][0]
        src_list.append(dst_node)

    def check_edge(self, src, dst):
        src_list = self.alist[src]
        dst_node = self.alist[dst][0]
        return dst_node in src_list

    def print_graph(self):
        for sublist in self.alist:
            for node in sublist:
                print(f"{node.data} -> ", end="")
            print()


# Example usage:
if __name__ == "__main__":
    graph = Graph()

    graph.add_node('A')
    graph.add_node('B')
    graph.add_node('C')
    graph.add_node('D')
    graph.add_node('E')

    graph.add_edge(0, 1)
    graph.add_edge(1, 2)
    graph.add_edge(1, 4)
    graph.add_edge(2, 3)
    graph.add_edge(2, 4)
    graph.add_edge(4, 0)
    graph.add_edge(4, 2)

    graph.print_graph()

    # To check edge existence:
    print(graph.check_edge(0, 1))  # Output: True


A -> B -> 
B -> C -> E -> 
C -> D -> E -> 
D -> 
E -> A -> C -> 
True
